language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: compile
      script: yarn build
    - stage: deploy
      if: branch = master
      provider: pages
      cleanup: false
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      local_dir: dist/
      on:
        branch: master
stages:
  - lint
  - test
  - compile
  - deploy
